resource "local_file" "pet-file" {
  for_each = var.filename1
  filename = each.value
  content  = random_pet.my-pet.id
}

resource "random_pet" "my-pet" {
  prefix    = var.prefix[1]
  separator = "."
  length    = "1"
}

output "pet-name" {
  value       = random_pet.my-pet.id
  description = "recorede the valur of pet ID generated by the random pet resource"
}
